### ISSUE TITLE
Omv2Avi

### ISSUE THREAD

**Issue by TimoZhou1024** [xmoezzz/SiglusExtract#25]
Omv2Avi.exe好像没办法转码体积较大的文件？
星之终途 里一个约700M的文件就无法转码，其他文件均可以

**Comment by xmoezzz** [comment]
Please provide files for debugging purposes

**Comment by EliGe15532** [comment]
I am in the same situation and the file is here:
https://1drv.ms/f/s!AksMgZiCtiuCZoeVurMxJ3LiM1o?e=TOn8lX

**Comment by EliGe15532** [comment]
> I am in the same situation as TimoZhou1024 said about the game Stella of The End and the file is here: https://1drv.ms/u/s!AksMgZiCtiuCaydU2q5KWKzCnn8?e=LOBN0B

**Comment by LogicDX342** [comment]
I'm having the same issue.

**Comment by xmoezzz** [comment]
This issue should be resolved with this newly developed tool:
https://github.com/xmoezzz/omvdecoder/releases/tag/v0.1.0

omvdecoder is an omv decoding tool written in Rust, which is cross-platform and supports multiple outputs. It supports directly converting omv files to mp4 (h264) files.


I will close this issue.
